extends Node

# GAME STRUCTURE
enum GAME_STATES {RUNNING, PAUSED, MENU, GAME_OVER}
enum STATS {CON, STR, DEX, FRC, TEC, MAG, LIGHT, DARK, VOYD}
enum TEAMS {PLAYER, ENEMY1, ENEMY2, ENEMY3}

# OUTFITS
enum OUTFIT_TYPES {HAT, HEAD, EYES, CLOAK, BODY}

# ITEMS
enum ITEM_TYPES {EMPTY, ALL, ARM, GEM, CONSUMABLE, KEY_ITEM}

# DAMAGE
enum PHYS_DMG_TYPES {BASH, SLASH, PIERCE}
enum MAG_DMG_TYPES {PURE, LIGHT, DARK, VOYD, FIRE, ICE, SHOCK}

# HANDS
enum IMBUEMENTS {NONE, MAGI, FIRE, ICE, SHOCK, LIGHT, DARK, VOYD}

# ARMAMENTS
enum ARMAMENT_TYPES {EMPTY, GLOVE, ARMBND, BRACELET}
enum ATTUNEMENTS {NONE, MIGHT, WISDOM, CLARITY}

# ARMS
enum SPELLS {NONE, FIREBALL, ICE1, BOULDER}
enum SPELL_TAGS {PROJECTILE, EFFECT, AOE, MELEE}
